apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-drive-prod
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:miruohotspring/cloud-drive-gitops.git
    targetRevision: main
    path: app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-drive-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
