---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-authentik-oidc
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAdqOiWsenXBNcCVWInuzOD8HZA1LMrAuO5BXvv6+4BOenKCyJozBsl4Zm4IM768Lj76z5wxFLrue0TpwkOauUjUGvbAzUuME2Bx7rGN66awsmQKIslSi5uaJC7NYN5jdPy0IQ1ododfOeUIUNNWuU99ba/erbAWRdQ07sWOQEru0OPysXBhH7Z69/Zs3nfjynajhKHfAAZA3Zpmaia1sewTgmqnVDvLC6pz0MejaBFmrZv+EprnAbMSeBNKJSx6S/TQX+bJqfEBVDZ5f5dBG/eQy0w1SR5ecFJHLtDUSNT5n/X8eYUHisYrwISxGF1d2l1HnbvwslZXSxfZsq9Kh1nX2utcWxqYrlAdttotlKIPoRKeVvM4YIa4iOs6oYFNaLo1a+1e2m/LKhyHHN5199Va7r5eIgHETFpJMhLMNNJkksss5xyh5RPEMKzlp1c2+vQ0ZVL+OcDFB9xwE9KaaUepPR1p5rX3iwUHPx3BLv844Ge2MKriXrhWzWTNxBesCEqG/ilawOPc2GPymREqYTXqvqxsjbRwh91PF/oOiChyz48Yb/RXOpdl6Pd4wWXEVDPYJXHCzkBbDPsUrIn5RdqU3akJlIe4BVUlCavgWVvvOCxclDfvm4WNPxIRmKZw5LOszSxGGuRjcuEtxNfiiJCKtsIMI6mBClOorXmurBGukXUecFChjTGg0O+2IcaGZPTNjdgx7jbrqhVAEXeKCP3rLRfxRWNLYfIgg/ce5um3zxekBIk/0RTl4GM6ZHF7GWdvk2tqCEN4Yd7ekxFM79hNTreW/vFOUn8LKj2EEMxk+VWH2N7cSTBpQ5UFqI5wLQZv0Cw4w4O/z3j8XkTQnaMcgb5OSbEqPEDu16uSFw8rw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-authentik-oidc
        app.kubernetes.io/part-of: argocd
      name: argocd-authentik-oidc
      namespace: argocd
    type: Opaque
