---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-cloud-drive-env
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_CLOUD_DRIVE_CLIENT_SECRET: AgBMOD/nJXzKVYY99jlH+fQ1u04AJcZL7cPysGu95uyN/GnWCkEwFioofQtS6P61fBSsppnwFDCq8TPmnp9Ai+qu1hnA1O8DJA09ut6ELQpHD7s2AnunDoRv2/2mwc3tdRh4JoGse484ysDfR8bnTc4b2S6kZhd40Ho7VZrbQkrrzDqOvxsKVNBDGKuyjrhiUBj/5OB2fCWCDbyJYc9/vHzlkWN5YESpUcOyEfwMPnhOhDtKgPST9uE1eoqL2O2BpB+hoKj/F9Ntcip3Clu+cLkn2fBinZABsQ/XhFReVp68BUUeybrCJKGsneOmaBfQXKoQPwp6CEJKGluZR/DdLb2ZO9fMay508vA7slc8bgmElQ8wRo0ktK2Wb7vxVAGKwWgtx/ELmTD4qb3JVdAZQv4FMidwkE0y6H93ab0sRvPRzwY+/rcOuGIFCoem0bNe+3W0UAqkCb/P6hgACyU1Pti1POPR07lOKL5Ihbs22QNAovpXef/jmEzeRiLX2niSCTdrAd1V+OBlEkIKqY0PsMY63PVivqGHJUdjMmPoZHdoWbWCYbKkiSvf5Bj1vh5NGywcDTIY8zFxhXllB7qcLOfr6RHb/rKIBrxCstuvMw5XMaySe8MTwy6FaQrLtorFFYiT2aWVG1kiZ3Dq6+6N/uySI+8IWOHQ6wfDdDIUpYW70h+HaGlsrj7YIvFhVzhVtS/FoplQG2DdBrQpRZke4QKPDhVNvPXOZWLkBGNHsI5kQXwaqTeQuryndlp687Bx2ktbSbFkWKJaseiEZU6tcy679Q==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-cloud-drive-env
      namespace: authentik
