---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-postgresql
  namespace: authentik
spec:
  encryptedData:
    password: AgCUfJZ56qZDhQe3s8ZiCZe0K6LaZCC7RbYrF0Atav4Fio6FHm+DjmDV/mfNuAvgw48fb3kO3XWvt+D29UjE2JkN434+rYFNKCa38uCHySoN8OdXXRCgTiN6xr6S/o5ieCgaG3j74yS+2D8gMjzHVpdwBrlgjRxqds/TIEEiqVnyTOaJbwaCV//dGV6DYSU7G3e9i+Npa5GpoxkkJPu9BOAmN91CaMNbrZjMJWa9KgE4OMsVNzFG2A5hrFvS+ldQ7+LnwFU0Hfg0Eaf8ftuNy57/6DzTaIlAwuAdYg+1dN6iTtpYp4QaScSYNPG9MiM1tkK02beDF1jp3Fb2U88FyP940w+QwMhBygQjNQgZp0KS7umgd9aeTgwiaPp6Aapmh9tdaqAYACrCujNlk4jtWoqJXzu1D3lmOUBMS0gaSVXkRYcpqFUe7nMZ+mViiDLpgg4GH/aEK+gqQuaBkZ6hMUUzWIKYATZLLdo2bh94NgbaiYSAiz9aUNIzBX/zd2mJLA8KEMx+gggugfS0ngJhR1vl0aK4hQ1T/hRzNttDxK+A5Kd5l9x9lOdFB1IfWEuXg/fFdnAwN79yr0+XNJBF74qROj9FZVkFRp5Uu5zKA/g+2RaB4x8bwk1ljsMdg36RmN4k5D+DBECeTETp+cXVRTwru2LhbcudS7U3LtgcJ+0Tv4vA4LFN5O33b7JLYl1G4F5B/nmov+nY+aeGcTNV+hZKN5H8CTw6H4fQ7Az9LKWa0gW5HYvWBqm7PuSgjxf/ObvWaDfd2nYs14wMtfh6a/ivO3yorWjUzsCVXUUif4Hx1s0IEcuD3pJgN2G/JQt7+PWTF9jkaTpU2Je8U4XzhzrWiavjQWVuoHyvRnssUpGALg==
    postgres-password: AgA/f2N+f3Evd6waMJnREXTNXx2qzNR17vKQMhHAiVN35cUWR8Kji+Y9TfpuKJqaNPCQS8LOBnVfYzHm9AmEH9pz0EMkxI2rZWOje+jUfOVWjHRMg52noMUllgJkAd+gy5o7SMdCNPT0WFTKju2AmqzeS7AbumUs40yxx0D89FvAuUcK598MdlWcb0yfogtvoc0cbCLzYoqPsp23M9zrDPtSthRjsQ+MdfdY3nvkQ5i0KFvFyau4budV1m1f5yoklebuLfY/NH6N6e/W0lGJCO83StrkRDViYIZUUiqOdi5UwKqC885bAf56GA/+tOYVWQ4EF6sQUb4zr6yxAMg/Y7NAABXh1SLsmQpTAVz5ekwUqYC8QFOJgw16avihLdk1lHQ9qdYX/aSe8T7dPjDxtttnOsveXrBTpghRRXBqxSU+M8LiNUjFeVm8Fy8YMuk01ilgE9bn2tUtXRaGOwOnwWtfWsI4uoEsQppsBcqoGAkg+BhM6PnguB4ATJ9n6TXRUogBfh6PtMjgD6t5XJ3GeFrvZmT33VpYQ9w6vIcPJA7RzhhbU91xh3dSaYDOyBQepo7oghq++3u3VfzV3w0sSYC/xl58vuw6JXxLhOrfyzSgWrgNeY4bNL1Ryl56w/f5PVcjMQt6ewBW6UxVAITn5BLU0EuZ4krtU0TVRu3BUNWoCvVn8W+3c1Mrpy1eFzoOjdgFC89pbkQ+C80GsHhX3E02usV3Ub+6U1bj4Wnymbuph0SseZUEvhuYrPMXQVscgxTcTNOQML+aCqKsStdPPJmQiiIxTPoUEDIMmDKZbO2pOvWo28nzhEjuDSbYO/2mC+zu7Jmy12/FdcJky2cwq16H6cHUvsDAOo7WfASYy4uilw==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-postgresql
      namespace: authentik
    type: Opaque
