---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-cloud-drive-env
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_CLOUD_DRIVE_CLIENT_SECRET: AgB5nUtefKTqXeEvAAItu9S+gBkmFI1H/TzJyEQdzuftWBmGmWElR4P0XWwyFA5pDTXzIUK7FP8ua6KkVddOK8cGiZJVmGNF1LZtjo6WbcpsDeqmVe4mtwLLcvwEF+bgpxYNuuWYlO3Stc3ymk6BIKAItBeKzOqyE4OI7n3bEhvr7GV5pDv7+A0Q9/a0uZ9aIm6Xcd10jAyAl+tXFGaz6goy/6xRgpe8tsk+pyLfVX8kQof5rE/jXGc0VxiFLvWRBT0QtIAeQYoys8xXJ6NTDCyzWNMq+jvH84ojUR90+qSx/WELxKXCxhrfQoleAk6Yc9qmV3Q0YBToKoRKrS9TvlJywSswTJc90/1ShkObLEGggvauIo4gGf+HmQYIL+d2SCByM6zvE3El/hc4U8GWvDRrs6ABVtnECcCj3WGVc7BXu+cDYkwULcvyy7xagWYM05igH5SrYzso52rdqz1nwjeRGbxnyQW7xZv50vFuzp2Pdkjr2txgN2koNEHuAGrwMalEpgIY3gVt9LE+zv6dWoFGvis9f0DErafGk2W1vqA9c35n6zvbjbYnvgEQmVHlZ+ORPoRuh2ZsI7tUh0Qtu0jIRioYKx3oRV4P7g9Zo3s4fZ3TM/oQoyfgkNhDIXBt8PtzaEQDhqQ4pJnU/QhIkKCLOnFl70lfE3fVzvbR4YWA2lz719iRDsOG2SA13PWPDF85icCBSTTgo+I5csq+TApLOKnasuJVith/JhG+fqkGfJRBpH6MPO9MsE+yZ2dY/Qa2s/FSp97RNawTW3e+SkYf
  template:
    metadata:
      creationTimestamp: null
      name: authentik-cloud-drive-env
      namespace: authentik
