---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-drive-github-ssh-app
  namespace: concourse-main
spec:
  encryptedData:
    private_key: AgBGqzpVpAJywv4EvXoboZ9Q4yh8ZXLn4SCfVmFd+dvOJ8QpGKj3uSJxOscZJGxEu4XVDbTucev8UVp9+fFRoc0zmhHmUYe/sx5p28WFq19zJgbYwU5UmJX/RCYzNtW7Rc4L5HrYV5on7kf54xNfIuhrvGkWL8bZgLYm/PWAhc5VjFSkDyQw3WJmbFfz0f7YiRfgLEjBQAhC6/poBlDeVcii6iDScNYWOwDSa9KUgFxJJizKBW7EpqNKm1qEE6i8Y1YZg/ChoVZKMecWGI2fnuX82voQIWtnpinuG4m5HOmQZ1V3KNC6dC3CeZk6ilzgwPRbgX5EZoKDyktTRhTR2g9idzDOiajNySYunoNimw3x7hcgJtmDxWl2ftg84re8iMnM8IOdndceY8NZNtIbqpupPBuFErtostwUq5kA/IugslM0ZgEsaXpiHuiiaN4roWoiBFprmjFehWX62y5EK4j8s/Mn8VZf1qb/ag9K44JqAgz7FDstUUhIy2PxIyo7Td34YbKgn0nXlN5iUngE30Q8KyPfWZux7pUMwmHW25aThizDoO5bhcv23IlWPWU9UEoXpzbkqeAYSkPm5Z7ATh0lAAI4t8KqgATE5NFv1xzv+xTfLlkm4w+QtsUUOFgdA8VtCHgzC8k1Ar2WmssRc8bYs009zsW5iR+bgh+0ovPoOPFMkRHHNRJVE7l9QDf2qfI/7bTh3bl8k7MQht1eVvG4jMUAzsMHWrxztmc/U55YVbO8QOY7UoQ/ow9DRpFj10E50wfDUtaXhbRtGwezJYhl9ai9zs24lCnK5vfcR6RIRui/8Y1GAbWNQoP+Kr0E+YzyRhD+IKh8xsV8qUSPGm0NdSl5DKYYyIjfXvAuJRGy5gT+jHEyixasAUKOpHMIbrEScfWsz5BpvLnY2hwBSv0ENrJ80AA81VvGG6KY/7mCxYUXHeyqHxjUSBN/sxhM/ajkv9IxEJAYWaKciGDaJj4Z0JP78IejagECDOzO8vvJ7cExp/sofPcIrEry/maVlqFUiMdgX9RShm6B3Y8P4b0ycKsXUKgXe5z9O6XiwR6U9550QmENCb6+27BqW8DInOk/DwA421GiVtJ6lqLoDV1RRV0iQRFEAThNgQknwVgDG1PkfI+Zr6yPb+P1H14AScrVawhbhT4th1laixUlg6I2dtALpJs37gp82J7MrN3i9VM8JeV9GWIZRqL0yO6mMPwMda2B2e/hsfR6870z+yiGBbMYu7hQsFeEoLB8hLAPDTYvAg==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-drive-github-ssh-app
      namespace: concourse-main
