---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-drive-github-ssh-gitops
  namespace: concourse-main
spec:
  encryptedData:
    private_key: AgCFblQkQfY6YnSpqV2C15Qt+GbSxCcCGf8xl07WldCvK0Soz2zXajwxVD9VRggB9kMZ3+P3c36lM4BVidK47idzTYyouV0AI6cExbOIFVjOd5TgLTVdCVFkBfQxvkjCPbYlV32lGBZAEvdlCJQed9doXPxJzWz7v2ybwo2m+NpJPPYpLPe1t99TP0paBytwkl4vCeFmwIHBXyseS6qsPAS8qL4LaGQblglCjlgBM1R3c/ONs53aUkj1+DjKTNBr0l1Ox1veeW0/LJx3w1H7XgfO7G6yvDT94o8ueLyFXgwaLbWy6VQja6Y0xEcmTd4LfOapo2hNkB2zM1bs5UVLh/T/JN4J3KlWPIpb9O+sZNfP87Lyc9eQuDpKZLv1eUsAXOK9qFbQYJ+ZACFe7GXg/DzYyI5iHWay1d/DpIWNzJYw0erVGVfCa+3VXDx6xpzP/OBR5UAWLYFbkfck2fsuKkZ5o5ubBww/CjKFm6MAwO7nMgmkTvvyRmAfWQ2KCRPjtX2VV9QP7jZccj510FuY5fFEtwqSZGI0/q9y/+HyH3IlMgjzBbhzPmwXJB843jXIOVxrMcwX8Q2XAWOkdT3DQzVikid9DRwuabwLNzhndvBF6P+YDHgO72rKBi9VdhZmE46wpT/HtSEjUpqPmLMuY4223G0DpMRrdp6tX4Vm5s0qspk91nr5At+tP5kgXg4ukY6J0RVZiP/KMjjTFJWE2KDLcafJ4Z4eKQ41726PF+4NsIazsW2iPcU6kvA4zvoyDRQWYY2QToAijO3UYnU1shePJI7PX9w4u/SZ/Za0BPUL2akaNiaMMGz1jelu1K/8lAFw0LYPwv9i1xF7lIkghli4oEOGiEcl1rocjKVyhaEeMBLze3hOgLpVDX+eTUCx0q+nUHhu3sYoT3B+Efesr+0L38i+h8dnNFpIV9RoeLl5v6VpZqLLD0hl2K7Bq0i515ytLCErmzMafkiTr3prS/xYlQdL4c44/eb2J9O1SfHDnAeIil8FiqfPbBmYZzKS9LrHUoYNr+OFOCXSLamipXQ7vU4MPoRTDv4eHDQ0ZmGGmVlO8ZPPtPewDIX0uQ35CE5olicVDMm1AiHFPTZ5BXGFkyMcoep6/eNarkC9O+YnVk2H2yRlab48ajbJ13UiEMa+K3SBlSWJBznL9eHvToZUjNwjFqwi72z9AHwqhAP/PkZy93DwK/DhFDhGzEmmeZHYXmK2W9P6g5sqSpcUjCsgsZxXKdp6SnvicTXuR9A65IP0dg==
  template:
    metadata:
      creationTimestamp: null
      name: cloud-drive-github-ssh-gitops
      namespace: concourse-main
