---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-drive-r2-state
  namespace: concourse-main
spec:
  encryptedData:
    access_key_id: AgAfkrn7cMkHvhOPnzyfeB89PbnQUI49//fYrh0U9+bp0+CC3K8OHhlZv7UsVf/u0jEW95QDphnD9v5F8c2Zi0tS3oh9M5fV3wydNmRZDfGj6DnFmuw5PNxFPhrqIkEYLwKM+lZShw95zqMp27V6MXKy+fBwUSARNDrJD6zgQFDNUjvRK1MMjX2UdVXGDbs6TgFt/Hh3Zk7ViSSN1l4n0K8mBDshEdHE2HYdvdHar9nku+VX2o6vbdILnhhfqoU7aRXcAzGy4uWTUmzTfOPXOGicqhDMWixVVATUpMzR3+vBwfwJNsRg3331mPg3Nxadv2gBIS5V0eYIumH0ZYLCgDs6mLMhT4Wn/lUPxMFEsbinrj+v/z1qezevTSuYFHzDFejn1N5TnCv6asUyp5/Goq/O9IiXtqugWpKZzq5mYJJhyKxVxH7BH6u91mMZEkhzBpRLG7z5YGlX5QdTrHsggOJ1d9H8sGmCWq1Lzr5qoV2W1Fo9j3jKrMvGO2rUPdiMeiez/0Lmu0f/1wzLXJlQ3eTMT6zBdxjGKdeOra3tB0GhhgYWemywxAxmSFXfOOC8eyTRvR90bp5EQaxgKy1jRgI4NEZdQRS0ZxvQVOQMHeifxd3kjZC4weccS511wbuaK42UU3Cn48VImJPWZYa1LYSgv9xQNdIQPM2wvfeK0HJ59rfJ8khIs46TOTKmBjlNYaWcoxZoFomOHz7VqpE1xf3LU4d6rSBFGGLxYFIf4lFd1A==
    secret_access_key: AgA5AljcdtGJhVTKTPOVz+cTqnKKV+8SRLRLUNuXR8D65TZaj+JXnjaAYd4QRF440hxIoj7uwh3WAu353ghzkJA+CgAky1HBuS+R0Q6YsrkIanIeWmETOkWv79h2AhKAXWAmEPgB/G+mMeLunwT1BD6Y0d+drKCAZGHnEqfCb+YHAI/XE7HqyDhOlX0AN/yguc5X/yzLNVIiQSehp7PKZwzKWzQ16lkX+45nbLYaXXuUsZ7wPvTvIqj2nFcY6BDcGgWwGrxfZ8cV12cDGw6Y3F8uuUV3O9KMGTWUSeyZI61zRvGTocZesROBflw9h4R2wR7g/7sSWXzftd7GfVL/832oAZdXXrUMFDecHd23v2CHWBWa0hIH0WMQzL+VSVVENw3ASkGiwepTczcoHmdhPcccPXSUO5czpzkZhrqC9L6X39MXuu8Uc6l6haZCFHaQZdzygsAFcTUNEDKzhnDAk86uiD+9SaPh21nVnOFiZYeiqoF4Tg5d5gyEOBvTg+jwou/MJw5lbQUqYPpMXguipAITaFPbvz8ShHPuFRGqV3DIn9hT9jPPCg6wZAT5SZfHm7fW3Eh1zwvzLuhPU8v0hcXrASYoo0J6mQKmGz6hXaz6+Lg2GKuo2MbqdPL/uGQHcYfKbWMIUxs5FwAI/mxkBDPQfzj9kU2hW0uR9zgLHs85jpwZYM3kRPjlW0neivn+a0Y7/Wa2yF3Hzpn6VFrYJC8FKzFxuadGuEodVsH0r53m3vnjksQcYr9sUiKw0RjbsHq0RMB2LmKbXBD9AGVxKpoG
  template:
    metadata:
      creationTimestamp: null
      name: cloud-drive-r2-state
      namespace: concourse-main
