---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: concourse-github-ssh
  namespace: concourse-main
spec:
  encryptedData:
    private_key: AgAyJBcG0KBfevPNANjaQhjFyEozoJwQoCul8q63v4XObg81qfWiQQimWlkAS7fcKGoWL7pjhfHJI6GpyaHa8pXahlOq50gSoLJVXsW/DJ34Y9zPx+hnVdguqPZKY+Sh7WJ6N3MNs7HgpjEhayY7mPp2qkK14KzuVw24y2u3OjRQiqG1x3+jIfGIMmDTMGxo2tiZtLc6q6WLSz+Q3CoAqQPQyqWW0tf6BbpmdyZbwjRUBUf7ibc5XhowRKZmIY2xT2DQk/HiorNRac++jPXqZhdq96IAZz+GnsjZg3M28gZzZOkBZbZyk8QTvKpbpExqAI2hSV0ouMRbey2/0bFbY9ImnEXi/QGr15ZpsvqzCtfhVZphmGEvE4GgzhQzHreYj/bTNa1lQRvUAqJlYxxIy2rK/tv6l9gl+2Gyb/uQGp2FUCPw6jOReho/FPjzIhjfJMTHfGCcYBDKemi5u6/YkuknL8MTT+7r5Agacnwd4RyNTS/LAC3uXxxO/ejvBZrPH9B0jNPMLOc9v2k0Jf7s+zUtHLjrdcdAV8JQAsY8gPbTKOboKH7+wS591UrThPtRb8Vfwh3CHL+1Ubjx2pfNiHLTqzXSH+6tcg3jPeLmmLs+Sn9ERCaGfi7ouSpCSQOPHekIKTWX3yHtLOp8XWIKaH0GTBoKSAdEOH/SfPko4L4Ms76u0vxWNKXxNo2rlPNv3+24Nj54jcbTwe/agnNWHDA9DbHk+IiVQZ8vadXBg7E2LyZdBkQYPtUFa5x4WHmLFRiryW+hD0nyzf8HdBgQ2rECTy+pGKzg+7yv1qFKKZCucGVxzFW4+ovWoQmcWzeqhqz3TpVT+hXA09mJZr2UoF46pLSDo9RoVeiRTe2FpHDt8M+BXW4L290addAFRgm1zzBFnf5irxlRhwWk+gueJ4hLlk8Z/LwXAbiYex7W9ZP8BDIu7ClLopUAVqWbyGnLtlsLjnvIiUVNWXgQxvDVBY1oKwkiJc14eScZw7xMxpUfLDYocfCo1h3NTgyoXYJgEV/YifuDrd512klH0CZIGHK2VnVlwt5TrXCEp3WB+Q0lFwl18aqZjapq3xxtsGjJ+VfV1xB0RlAD3Mr9R7Xq/lNcwP3tlv8d1HpEUBfVsVTUksQ0jX4f3k+KRKWitWC5wTGMi79AuqpD9GSZ0b4yBtYlh4nxIOpNB6vM69ReUNN2Ky5zbs8Q10xOLTJhkt9KSKVbFixjxejHYW8/YvueRMb8MApP6Szj+r2AtvH2nS0Q66xGgVmGK9yrpayNXQrKPT1KwpVL1E18x/iIBzs=
  template:
    metadata:
      creationTimestamp: null
      name: concourse-github-ssh
      namespace: concourse-main