---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: concourse-github-ssh
  namespace: concourse-main
spec:
  encryptedData:
    private_key: AgBuJIvRAH57Ob7IGCrRr9fk7UEZmM7E+8y8FDSjNKdAadhrTbaNjsE9V5Yqg8g1rUf0ApiX+/YavoYH4PUZpQgPz47joZPlDE4cml++22lNkRom0fp57n0y762Ljv/GOKrrzxjir/CfOR0sdmMiccchfVUgVe5JKPWH/WrJSVJbLpZDvGrZJ5driJ13oJ4xLNzZBYOwtd6fyAmcE53T6HEy8SfdV8x2LrALhEXEiknmLEtVlpJ3ZmMa5rGnMinMWJF6QgTRAtIZy77h3hS6GIwAIwdmv+ia/LD6s2Ogp9vAECIWad2bPU1ZmiTNUPEmLq1CPi5zSxaUvt4bHvQVL8ybDcrJC58cqBUch1xh1nljUIni/njBG2AbJibh0OuZP5Lxwc859lOPsfLWFZUYgxzg1OOoyQU2h8BWbYJ2gdbdvN210iKxfiYlTxRMJ7BUKjpM0OXIYKKnQ28SpS7xeYoQcDQIYsAP4F5thVdegSZE2Okrt+4Gcq/9VS+gJDdgo6LdOpiBaDcayP5+hBtL4tiwy8xlyo8FzfzhAIF7dzGED3N8wopwFjjE5lwM4v71LWk/FiUTmxAgjO6wyLKFjJQsk1FO+d7bYSpTbBpqAMSVtGVcyHZo9vBbYsszdFcqbQHUdAIovT4odBwWoSKQUI2ONmDcsahaMd+bXvwlp43qIo5XipRNUZS8DYTq4fNfLeMG8BjNCKlrFdluxNjB64p7XwYvDDiNRxAOo/KOsjlBtUKeDg4JmpjhKeYG1v4WQDSeKOkgKaRd5J58c2QuKT59lT0vL1d8nEduxUoWAPyz+PmP3hsoKI4xUOwiCGzX7j37qlnAbHovmcre983dE+Nl7O6u/zzGcroKTaoRrfx39MjyYDNWzGMPOAv67OtrpeoOGlNXK5XNgLrFEi2BypaapfAGHvR+OIs=
  template:
    metadata:
      creationTimestamp: null
      name: concourse-github-ssh
      namespace: concourse-main