---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: concourse-github-ssh
  namespace: concourse
spec:
  encryptedData:
    private_key: AgBs5VE/NB/blkcRX5ZxhhQv2VkcUHpgnyekrnldo2U7rn5XCKE6vr7wNxa2+AG0kVJ/9bgAtSrzO4ZrhP+SSIeSONPL+uJma8+SR1IFAEtw8rurhKDU/EblDDAFUCMygmRhK2NXOkfW5vqm6IA9B36OXqdFqSxBatVFMbiwM3XbBVuTLN8dnXNnslCsf2diLMiMaq7Mryb6oXkDHql4Nzx7dRKTh7UxHUHSZy5+QorbgIqll6K+88mLmAp7ObxCMP5799RwpoJqMIth6rnFuCn8fRMPp6s/Li7ClDwp+8SPFrlU4Gp5EZlplogM111qR4GsoS/ye7gD2Dy3m0ajizRDbIJH1EeuTHkndc6oevdK4qe91uWqSfdp3pv71W1RBcSqA8aZ0kmDh+zn2EeSz/Z+rOcYt4JgKQWqsBEWqCjtxGPgz6YCkTwUz4sJjlaS9f5R6O8gN3LdkNw0tR4wZqjScOs7pxK5DtCFY5JceOImkH/2DlNqzk2G6pNjQzZWzoHAMnc0aclUYUdbXVxrUAfuswYX6yg+W/A2383xiaMKvFVuFzvTObzwF4E9/uK5yCVBjnzLIhd0T/vheZFyg94ZH27D4AQPZBCLCdX/MS1c87Siiz9eO6lgXrZOfqs2b2YhY4cSrNgckztCdlJ3VVHrxWC2bNM7vvyVTwJIW3l14sz2AoP/xWiKmqrj39u5xhfbr7SsTOoT955EteTJlwGf8YqSdJAP9043V1jEA/+5HdUkThwXglqGLbgfkrjMTUG2WxhogB+cYOnnEG9qeYh4Xz7Dxp9e4kpKJV0A8kLQa3MLn4UQI7Xg3tWRDJvDWw0qrvp5iUajs4Pz0QpdNLgmisOlsT9vZwuJMB1pD+G0zqlohVScEQ9dr8UUZXx+drbGjU39nu9ELo4089Bd32tckD0c+gavEnCstd6oV8fe3CyxDbIzFIwIouwqIR2dLDA+twO6AXIPB7WMbD/bM9WWjzB8P9eClptyKv+byZ4PmdkkM88FtOLR2JnqlVFHaz20kUZsqVms8rzT48k4cAMDM1OyMwdQlfGSLhmq2VEoSpufSfi+uEhzV+dXymW5pPTP3Lzp8BEP3POcLwSgLQ/KlqOhvwm+Rn2te1dPA8tfmaY9j55tTwiWeWHPM/aq/Ws+0A7ClLrZj/JjuNgLflkh+2Nwhuz0faxzQxtGfvOgWNSgYVCLTHA3wE+kxWWDJmuoUcSb/rxyymwiw8Cu8Zp9Zma6Pok2oepVAfnAfSS/75LQJsTiOwG4iZurXc3t1/U=
  template:
    metadata:
      creationTimestamp: null
      name: concourse-github-ssh
      namespace: concourse
