---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: web-app-template-github-ssh-gitops
  namespace: concourse-main
spec:
  encryptedData:
    private_key: AgCR7e0xeDU21FvYZOfP+eaqoUJb9S/Y/LGDqtBLieei8I0istINj4yyfxEW4qG9s0pLkK4N33y5ns8IdbEwJLSnckzRVDmRQPc73nHtBYpN45MX5Bltko0Y+tgBKILBdgSIxH4peqfVSsZmCn61Fbwam0+UcBpDDcBOKm36dw3/mdVgvTd/iwvcbWqTmOexT2MGmkwvdbVI0p2uNc/NdwujjtONEuLSby/naSmHn/eI0PF6NvmM0XvTiy188BvotA7uxKI+Ptb56oZNoLSVfwurO9BSO+RztOzpDp+frzGiZwDFWhu0p+QlTb8Wke62cattK+4T2bfiwpC9SXamTxoQI3ci2ZJo7RkfXfChWM9yJX2/t1q5Jg6+KXNhjO3eFlNcDKTC/KLjzddr1EKDgqI+5zLRV/UHZvsZ9Dcamfv5KTmoN7oZ3xFy8c5FAnrVW9GwZe8DUg2VVbIgqcuKbm+9NfWRZWdwcedfLUtNl0FOISiW5zantaTl8WCBqeA3hU550Z56dU4/FYVhMcU4Q7BRbjOpq3neUL9kHnkleHJrECwHvBJmyAUDbv7XkYxpHsr6rzyL9gBdetQ4DerfJBxwT2WIKT9h2bn0SpVpP7iiPkOr8Bb7VFN9jpflrMHeclFNljvDzpx8+wTNdOuMbBmJr2cvhSvz4zuXbiz9xipj3kaCyBa/+7181AApknsidWOA8yiyodXYyqiFVSskmyXk7262egGMO3avJ14lVYZeYb7YR+Za5nPHrHNxy9K0XIvyFJH8ooZNQ8wQs9fmL/wDhrJ9/Wt3UEzBk1WHWdbbJ2+3Stf7Jfq3z3E+2hyGfXRWB9d8hxNkZWhGGAviaJ0pnPYGOoEEgxxbw4/yrLrlT3IpHNZLB/brTNPCLFlv2DTqcJh2ZhUZm91poykjOhUr/rGh16P6A6ezE1sGePUsk5bXV3GpLoyeECboYNYzRN9jYVCqnNLPHTfX3Hiy7y9ermf6jF49V7gcQjg87NTLtkNn2hwyhgtCPYmCTbUTr/ovdnOWWyCrbX4k6D/pX+oji6Hz2xoJYuHdvZvdZCifozICC/7IXqPxtb9q8yPXK6CmYDPzArpy1lWLPcL880QehtLd56uK0gaxulJ1iT0Y1VUdUNcecmwpsN92EisWKBUVhjyrQx05I1DhxRk2yKzzE0ecuz05UCtRtUfi4WoWkkUiHUQy9F4CR3KDP+Yw5Iym9CdALNFjWfzJvUTS5l6Hs37GGPi5G0R1KKC+PK4tl31eAnMLnx9UwUJTtrpCL30l6ofkUg04D18xKGE=
  template:
    metadata:
      creationTimestamp: null
      name: web-app-template-github-ssh-gitops
      namespace: concourse-main