---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: web-app-template-github-ssh-app
  namespace: concourse-main
spec:
  encryptedData:
    private_key: AgBWp4mx0qzZ3YTD3RdtBHza1qTa4PtEw26Dmn3yM/BDxbdFPn3gd52Q9s4aoHFftOOIvT+VetJRZ157A1viB8vkqdCN6sFpW4Gb5NZUMrRbv/cxzF7JfLWAAnjrCkDBa4j/Ao1GS6fK9Xw/tLg7JflvvwqlXJbpz1Lr91mesqaqgxtyfqbS9VrrrTV/8rPNmlUQZ/oae66Oc7PK2HPv7XCw6PqOOZgUSFRGWLYYNuozLkxOw8bklwX1yaielrMSuAjvqR1W3qmYZpfzOOoEcdbBHmEmX25XAhTYiUUf4eMuahQ0kSEioepkYPKXJ8lZeMofXMeq+UMrxBfkbXrEIDu5vM7125ATEkcwB6sAqUGnHZfpqQgb/JNXctPuZM7OLroKx87pwQ8RGbuo9lXNIHknwYy3se8MGwNTr6LT98APCYJmqHFcCGaKQ6QWXwQTIgi7/0kZVMeKlx36ld4xf7Snq2Ss0PsUFILZwgJVBHIbOH5Fg4XlD2mDJ3xYAEaq1pVxhAZJmkYJH5svSF5hfgwM/QVeEJADkQezeqWCL3JZNG+g8UOcp71JKh6ON8tSjodZhG6zKqpZWx7HrgQbp2KfOp8g3vq1anMCqV0OTPjVX934lWbSsZqQYkyj3nf78MP0wmN3xgKfx8Eai/aYp4SuhFD8tDSsoJF95hz85pnZE6kdOf/yAhhVz174RWH6rbTNwV3zB3ARrr5xtVxEW/T9vRFlqNPELc00lh6uGDt2ZHn9bOzVkQsVCmkUsbR0HjFY6KWxhK6E0xMa0aA8WqQFXPXXdZnbGnJtRmc/IToj7lxsEOTP6lJBrdojlmp35qocB0sWnSnLAyeiveAQeNau1A8M1a/e4B6J6IZU+Z6aQvmFzE5b8DN/5e2bR2ID7Pz3lL9sbasDCRgbi4PzopGVlX1cw5E7UReaKjGsQUcVlgKSZK0MWJYnZVGhM+rq3wl7oBnpLJKZKJsQQMe7RwCXkFqxAJIkDrmRtF0wrfAfw113blysaiW+viMahmTpklUUcovNMgeosfFP9B7Y3TPXvsLUOF3o/FoJl2ViofYydz28ByvvZOjhZEjE6NNW/9bCdRUPTtd8QreqBZoS+NX0BO4pYs/c9SMO1timuX4DSdaSGyBnDGSrBjeykL9xkLC0QXkKoSOehRdoi8NSeiRgd0ZgU9OF0D9H1Fl1ylzXlcK93qqf7HXsvKZJJ8v9r5xMSK/nUDtfnnir3CHiHrDIxRaGBxwt6ELDdXEsKJqi67ghiptNteF6tmNN36OkR+cTDVJ7E2Kl78/BIkg=
  template:
    metadata:
      creationTimestamp: null
      name: web-app-template-github-ssh-app
      namespace: concourse-main