apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse-web-secrets-reader
  namespace: concourse
subjects:
  - kind: ServiceAccount
    name: concourse-web
    namespace: concourse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: concourse-web
