concourse:
  web:
    externalUrl: https://concourse.miruohotspring.net
    kubernetes:
      enabled: true
    auth:
      mainTeam:
        localUser: admin
    localAuth:
      enabled: true

worker:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

web:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - concourse.miruohotspring.net

postgresql:
  enabled: true
  image: "postgres"
  imageTag: "17.6"
  version: 17
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  persistence:
    enabled: true
    storageClass: local-path
    resources:
      requests:
        storage: 10Gi

secrets:
  # SealedSecretを使う
  create: false
