apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: m3usick-dev
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/gammaLaboratory/jarvis-miruo-v2.git
    targetRevision: main
    path: projects/m3usick/app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: m3usick-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
