apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-defaults
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:miruohotspring/k8s-home.git
    targetRevision: main
    path: infra/manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
